# I should be able to filters posts and users by id to get an individual one via args

directive @upper on FIELD_DEFINITION
directive @isUser on FIELD_DEFINITION

type Query {
    user: User!
    posts(showOwnPosts: Boolean = false): [Post]!
}

type Mutation {
    signup(name: String!, email: String!, password: String!): User!
    login(email: String!, password: String!): User!
    createPost(title: String, body: String): Post!
    editPost(_id: ID!, title: String, body: String, published: Boolean): Post!
    deletePost(_id: ID!): Post!
    createComment(postId: ID!, parentId: ID, text: String!): Comment!
    editComment(_id: ID!, text: String!): Comment!
    deleteComment(_id: ID!): Comment!
}

type Subscription {
    comments(postId: ID!): Comment!
}

type User {
    _id: ID!
    name: String! 
    email: String @isUser # I don't like this approach because it messes up the sign up request
    authToken: String
    posts: [Post]!
}

type Post {
    _id: ID!
    title: String!
    body: String!
    published: Boolean!
    author: User!
    comments: [Comment]!
    createdAt: String!
    updatedAt: String!
}

type Comment {
    _id: ID!
    text: String!
    parent: Comment
    post: Post!
    author: User!
    createdAt: String!
    updatedAt: String!
}